CMakeLists.txt
fuzz/packet.cc
include/quicly.h
include/quicly/frame.h
misc/build_libFuzzer.sh

Note: this relies on https://github.com/h2o/picotls/pull/74 being merged. I will add a commit refreshing picotls when and if that PR is merged.

Add a packet fuzzer

---

t/udpfw.c

Adds -d and -D options. Renames buffer size options to -b and -B.

Add drop list functionality

---

include/quicly/frame.h
lib/quicly.c
parselog.py

also fixes a buffer overrun error while emitting a CRYPTO frame.

ACK handshake packets immediately

---

include/quicly/sentmap.h
lib/quicly.c
lib/sentmap.c
t/sentmap.c

At the moment, sentmap is a list of frame-level objects. Each frame-level object in sentmap contains PN, sent_at, ack_epoch, etc. Size of `quicly_sent_t` is 48 bytes.
This PR splits packet-level information and frame level information. Sentmap is a list of packet_header followed by any number of frame-level objects. Size of `quicly_sent_t` becomes 32 bytes. In addition, byte-in-flight counter is integrated into sentmap, thereby reducing the need for a separate sentmap entry (i.e. `quicly_sent_t::data.cc`).
The change typically reduces the memory footprint of sentmap; footprint decreases from 96 bytes to 64 bytes when one retransmittable frame is sent in a packet. The difference gets bigger if multiple frames are included in one packet.
The only case that increases memory footprint is when …

improve memory efficiency of sentmap

---

src/cli.c

Instead of doing `5> event-log-file`, users are expected to use `-e event-log-file`.
It turns out that the OSX environment of Travis CI uses file descriptor 5 for some other purpose, and we can run the tests successfully without this change.
cc @janaiyengar

specify event log file as command line option

---

include/quicly.h
lib/quicly.c
src/cli.c
t/loss.c
t/simple.c
t/stream-concurrency.c

* retain and check TP.ODCID
* issue different server CID
* regenerate Initial keys

implement Retry correctly

---

lib/quicly.c

Replace some "magic numbers" by the corresponding constants.

Use QUICLY_EPOCH_* constants

---

t/e2e.t

The intent is to be able to diagnose what happened in case of test failure, like the one that was reported in the CI process of #100 (which got resolved by rerunning the tests).

create wrapper function for complex tests that emit diag on failure

---

lib/quicly.c

Signed-off-by: Benjamin Hesmans <benjamin.hesmans@tessares.net>

Fix build warning

---

examples/echo.c

@janaiyengar I think this works, but I'd appreciate if you could check.

[echo server] support multiple connections

---

lib/quicly.c

follows the API change to be introduced by https://github.com/h2o/picotls/pull/228.

obtain handshake write key when receiving ServerHello

---

quicly.xcodeproj/project.pbxproj
t/e2e.t

apply https://github.com/h2o/picotls/pull/233 as well as add covering tests at quicly level.

fix 0rtt-vs-hrr issues

---

include/quicly/loss.h
lib/quicly.c

Resolves type conversion warnings.

fix compiler warnings

---

include/quicly/loss.h
lib/quicly.c

Fix up a few things with sending on timeout

---

t/loss.c

The PRNG is used to generate a loss pattern that drops X packets per every Y packets.  The loss generation is applied independently on each direction.
That means that when (X,Y)=(3,4) (75% loss), number of consecutive losses would be limited to 6 (i.e., 1-0-0-0-0-0-0-1).
Now the 75% downstream loss + 0% upstream loss tests pass well below 30 seconds (25ms latency); 
50% downstream + 50% upstream loss tests pass below 30 seconds too.
75% downstream + 75% upstream loss tests are currently disabled; I think we can revive that once we start retransmitting ACKs every PTO (even when not a single packet has been received).
Partial fix for #151.

[loss test] drop X per every Y packets so as to avoid timeout

---

include/quicly/maxsender.h
lib/quicly.c

in case of late ACK or expiration after 3-PTO.

 fix incorrect state transition in maxsender

---

lib/quicly.c

Cleanup the picotls context as well on connection close

quicly per connection leak

---

include/quicly.h
lib/quicly.c

Assert return len >0 after egress emit

---

include/quicly.h
include/quicly/defaults.h
lib/defaults.c
lib/quicly.c
t/test.c

The changes are explained in the review comments shown below.

[crypto offload] expose keys, communicate key phase

---

.travis.yml

Update ubuntu used on Travis CI to bionic

---

src/cli.c

`-b` option sets the UDP buffer size (both SO_SNDBUF and SO_RCVBUF).
`-O` option suppresses the output, and therefore useful for eliminating the cost of emitting incoming data when doing benchmarks.

Adds two options for performance tuning / benchmarking

---

include/quicly.h
lib/quicly.c

As suggested in the review comment of https://github.com/h2o/quicly/pull/280/, this PR adds doc-comments.

Add comments (amends #280)

---

include/quicly/constants.h
include/quicly/loss.h
lib/quicly.c
lib/sentmap.c

Fix RTT calculations

---

include/quicly.h
lib/quicly.c
quicly-probes.d
src/cli.c

IMO this would be a good stats for checking that we aren't sending too aggressively.

add stats counter for late acks

---

src/cli.c
t/e2e.t

add test for handling of invalid retry token

---

misc/find-cids.py
misc/quictrace-adapter.py

Update quictrace adapter and add a script to find CIDs in a trace

---

misc/quictrace-adapter.py

I need to fix the logging to log encryption levels with packet receive and loss events. In the meanwhile, fixing the adapter so it works with quictrace.
Cc: @gfx

Fix missing encryption levels

---

examples/echo.c
include/quicly/constants.h
include/quicly/frame.h
include/quicly/sentmap.h
lib/frame.c
lib/quicly.c
src/cli.c
t/loss.c
t/ranges.c
t/simple.c
t/test.c

Counterpart of https://github.com/h2o/picotls/pull/301.

use PTLS_BUILD_ASSERT, _ELEMENTS_OF

---

lib/quicly.c

ACK processing of quicly suffers when there are packets that are not acked, due to the following design:
* When processing an ACK, iterate through sentmap entries from the beginning.
* Retain unacked sentmap entries for 4 PTO (to process late acks).
This design is fine, based on the assumption that for high bandwidth connections, there would be relatively few number of losses per each RTT in average (e.g., far below 1).
However, in #244, we started injecting gaps in PNs, at an average of once per 256 packets, as a measure to defend against optimistic ACK attacks. That has caused performance degradation.
The reason is because the frequency is fixed to once per 256 packets, regardless of the CWND. When the CWND is large, this creates more than handful number of unacked entries at the …

reduce number of gaps injected for preventing optimistic ack attacks

---

lib/quicly.c

Use the min of 3x limit or congestion window when sending.

Check for IW in addition to 3x amplification

---

include/quicly.h
include/quicly/cc.h
include/quicly/loss.h
lib/quicly.c
misc/probe2trace.pl
quicly-probes.d
src/cli.c

Start logging of connection-level stats.

Start generating connection stats

---

include/quicly.h
include/quicly/cc.h
lib/cc-reno.c
lib/quicly.c
misc/probe2trace.pl

Not yet adding them to `probe2trace.pl`; I'll do that in one shot at the end.

Add congestion control stats to connection stats

---

include/quicly.h
lib/defaults.c
lib/quicly.c

See also https://github.com/h2o/h2o/pull/2395.

let amplification limit be a configurable parameter

---

include/quicly.h
include/quicly/constants.h
lib/defaults.c
lib/quicly.c
src/cli.c
t/e2e.t
t/test.c

Support multiple draft versions

---

examples/echo.c

Check input length before echo

---

lib/quicly.c

Send CONNECTION_CLOSE in all available epochs

---

misc/qlog-adapter.py

Our current QLog output format is a mix of `draft-01` and `draft-02-wip`. In other words, invalid. Now that `draft-02` is finalized, this PR updates the `qlog-adapter` script to render payloads that comply with `draft-02`. To be specific, the [NDJSON format mapping](https://quiclog.github.io/internet-drafts/draft02/draft-marx-qlog-main-schema.html#name-qlog-to-ndjson-mapping) is implemented. Here's a cropped rendering from QVis:

QLog draft-02 support

---

include/quicly/loss.h
lib/loss.c
lib/quicly.c

Make sure the error is propagated callers

`quicly_sentmap_update` failing is a fatal error

---

include/quicly.h
lib/quicly.c

public API for changing CC

---

lib/quicly.c

We have said that in quicly, DATAGRAM frames are exempt from CC. That's true for `quicly_get_first_timeout` in sense that it returns a time in the past whenever a DATAGRAM frame is being registered to be sent so that`quicly_send` would be invoked immediately.
However, `_do_allocate_frame` function, which is called from `quicly_send`, consults current send window and refuses to prepare packet image for DATAGRAM frame when current send window is negative. This PR removes that check for DATAGRAM frames.
FWIW, in the future, we might want to add a mode that sends DATAGRAM frames within the send window. But that flag should affect all of the following:
* timeout value returned by `quicly_get_first_timeout`
* argument to `do_allocate_frame` function regarding if DATAGRAM frame is exempt from CC …

exempt DATAGRAM frame from CC (as we have promised)

---

.github/workflows/ci.yml
misc/docker-ci.mk

* https://github.com/h2o/picotls/pull/369
* https://github.com/h2o/h2o/pull/2891

[ci] add "asan" scenario to test the project with ASan

---

misc/qlog-adapter.py

According to the [qlog draft](https://quicwg.org/qlog/draft-ietf-quic-qlog-quic-events.html#name-packetheader), packet header can include `length` field but qlog-adapter currently does not emit it.

qlog-adapter: Add length to packet send/recv event

---

CMakeLists.txt
quicly.xcodeproj/project.pbxproj
t/test.c

Adopts changes due to https://github.com/h2o/picotls/pull/437.

follow the changes due to addition of ECH

---

.github/workflows/ci.yml

[CI] run asan on ubuntu 22.04

---

lib/quicly.c

NEW_TOKEN from a client is PROTOCOL_VIOLATION

---

t/e2e.t

this might be flaky but is working atm

add tests for jumpstart

---

src/cli.c

Incorporates https://github.com/h2o/picotls/pull/551.

[cli] add support for mlkem

---

include/quicly.h
lib/quicly.c
src/cli.c

see https://github.com/h2o/picotls/pull/553

sampling-based tracing through Unix sockets
